### All Categories
GET http://localhost:3000/api/v1/categories/all HTTP/1.1

### Create Category
POST http://localhost:3000/api/v1/categories/ HTTP/1.1

### Get Category with ID
GET http://localhost:3000/api/v1/categories/:22 HTTP/1.1

### Update Category
PUT http://localhost:3000/api/v1/categories/:22 HTTP/1.1

### Delete Category
DELETE http://localhost:3000/api/v1/categories/:22 HTTP/1.1