### User Register
POST http://localhost:3000/api/v1/users/register HTTP/1.1
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "firstName": "shiva",
  "lastName": "sharath",
  "password": "12345678",
  "email": "shiva@example.com"
}
### User Logins
POST http://localhost:3000/api/v1/users/login HTTP/1.1
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "firstName": "shiva",
  "lastName": "sharath",
  "password": "12345678",
  "email": "shiva@example.com"
}

### User Profile
GET http://localhost:3000/api/v1/users/profile HTTP/1.1
Content-Type: application/json,
Accept: application/json,
withCredentials: true,
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NzE2Njc0NmUzMGFhZmUyMTlhZmZmNGMiLCJpYXQiOjE3Mjk1MjUyOTMsImV4cCI6MTcyOTUzOTY5M30.Bg02Yp6ArJLH3HMtHNSMXEpYiO8unzOWjRIDe_GqJZ4

### User Logout
GET http://localhost:3000/api/v1/users/logout HTTP/1.1

### All Users
GET http://localhost:3000/api/v1/users HTTP/1.1

### Delete Users
DELETE http://localhost:3000/api/v1/users/66fc32870250de5eb064a04d HTTP/1.1
Content-Type: application/json,
Accept: application/json,
withCredentials: true,
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NmZjMzI4NzAyNTBkZTVlYjA2NGEwNGQiLCJpYXQiOjE3MjgwNDQ5NTgsImV4cCI6MTcyODA1OTM1OH0.L6Ax-ZS69PHJVZPCZffyOOqktDx9Ecekitv7mBSYp4c

### Update User
PUT http://localhost:3000/api/v1/users/:12 HTTP/1.1

### Profile Avatar
POST http://localhost:3000/api/v1/users/67166746e30aafe219afff4c/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NzE2Njc0NmUzMGFhZmUyMTlhZmZmNGMiLCJpYXQiOjE3Mjk1MjUyOTMsImV4cCI6MTcyOTUzOTY5M30.Bg02Yp6ArJLH3HMtHNSMXEpYiO8unzOWjRIDe_GqJZ4
Content-Type: multipart/form-data; boundary=----myBoundary12345

------myBoundary12345
Content-Disposition: form-data; name="avatar"; filename="17-Firewatch-Art.jpg"
Content-Type: image/jpeg

< /home/cybersamurai/Pictures/17-Firewatch-Art.jpg
------myBoundary12345--